### ISSUE TITLE
중성검색 제외 가능한가요?

### ISSUE THREAD

**Issue by rkd2003** [DevWookddu/hangul-chosung-search-js#1]
안녕하세요. 초성검색 쓰려 검색하다가 우연히 들어왔습니다. 마른 땅에 단비를 만난 느낌입니다.

코딩에 대해 잘 모르는터라 이렇게 해 주신 것을 개인적으로 사용하려 하는데요, 다만... 혹시 중성제외한 검색도 추가해주실 수 있나요?

캘린더 / 더 리더

라는 항목이 있다면, '리더' 라고 검색하면 '캘린더'도 뜨는데... 이게 뜨지 않고, '더 리더'만 검색되면 좋겠습니다.

혹시 가능할까요?

**Comment by DevWookddu** [comment]
빠른 시일내에 기능 추가할게요 :)

**Comment by DevWookddu** [comment]
> 안녕하세요. 초성검색 쓰려 검색하다가 우연히 들어왔습니다. 마른 땅에 단비를 만난 느낌입니다.
> 
> 코딩에 대해 잘 모르는터라 이렇게 해 주신 것을 개인적으로 사용하려 하는데요, 다만... 혹시 중성제외한 검색도 추가해주실 수 있나요?
> 
> 캘린더 / 더 리더
> 
> 라는 항목이 있다면, '리더' 라고 검색하면 '캘린더'도 뜨는데... 이게 뜨지 않고, '더 리더'만 검색되면 좋겠습니다.
> 
> 혹시 가능할까요?

기능 추가하여 버전 업데이트 해두었습니다 :)

각 함수별로 3번째 파라미터로 true를 넘겨주면, 초성 이후에 정확히 일치하여야 반환하도록 처리하였습니다.

간단하게 테스트 진행하였으나, 문제 발생시 추가 댓글달아주세요

**Comment by rkd2003** [comment]
잘 작동합니다. 감사합니다! 마법이네요ㅎㅎㅎ

**Comment by DevWookddu** [comment]
> 잘 작동합니다. 감사합니다! 마법이네요ㅎㅎㅎ

버그가 있었어서 최신으로 받아주세요~!

**Comment by rkd2003** [comment]
고맙습니다~^^
