### ISSUE TITLE
같은 단어는 중복검색이 안 됩니다.

### ISSUE THREAD

**Issue by rkd2003** [DevWookddu/hangul-chosung-search-js#2]
안녕하세요, 개발자님.
만들어주신 자료 정말 잘 사용하고 있습니다.

사용중에 의도하신 건지는 모르겠습니다만,
같은 단어는 중복하여 검색결과가 나오지 않는 것을 발견하여 혹시나 싶어서 글을 올렸습니다.

[사과,사과,사과,감나무,배,바나나]
에서 사과를 검색하면

[사과,사과,사과]가 아니라
[사과]가 나옵니다.

물론 이대로도 잘 쓰고 있습니다만, 나중에라도 혹시 이 사항에 대해 알아차리시는 일이 있을까 싶어서 올려봤습니다.

자료 정말 감사히 잘 쓰고 있습니다.
감사합니다.

**Comment by DevWookddu** [comment]
ChosungSearch.searchList('사과', ['사과', '사과', '사과', '석관', '석궁'])

result: ['사과', '사과', '사과']로 나오고 있습니다.

중복처리 로직을 별도 처리하고 계신지 확인 부탁드립니다.

**Comment by rkd2003** [comment]
아 맞네요. 제가 잘못 알았습니다. 고맙습니다^^;
